languageCode = "en"
languageName = "English"
weight = 1
title = "Janik"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
   name = "Janik"
   image = "profile.JPG"
   headline = "Research associate / PhD candidate at [KIT](https://www.kit.edu/english/index.php)"
   bio = "Research associate / PhD candidate at [KIT](https://www.kit.edu/english/index.php)"
   links = [
     { email = "mailto:janikbischoff@icloud.com" },
     { github = "https://github.com/j4n1k" },
     { medium = "https://medium.com/@beware-sim" },
     { linkedin = "https://www.linkedin.com/in/janik-b-996a5617b/"}
  ]
